// `code`     — internal slug, used as the Firestore document id.
// `bankCode` — official Bank Indonesia / SKNBI transfer code (kode kliring).
// `ewallet`  — true for digital wallets, which have no fixed clearing code.
export const MASTER_BANKS = [
  // Bank BUMN & bank umum utama
  { code: 'bri',                 name: 'BRI',                         bankCode: '002' },
  { code: 'mandiri',             name: 'Mandiri',                     bankCode: '008' },
  { code: 'bni',                 name: 'BNI',                         bankCode: '009' },
  { code: 'btn',                 name: 'BTN',                         bankCode: '200' },
  { code: 'bca',                 name: 'BCA',                         bankCode: '014' },
  { code: 'cimb-niaga',          name: 'CIMB Niaga',                  bankCode: '022' },
  { code: 'danamon',             name: 'Danamon',                     bankCode: '011' },
  { code: 'permata',             name: 'Permata Bank',                bankCode: '013' },
  { code: 'panin',               name: 'Panin Bank',                  bankCode: '019' },
  { code: 'ocbc-nisp',           name: 'OCBC NISP',                   bankCode: '028' },
  { code: 'maybank',             name: 'Maybank Indonesia',           bankCode: '016' },
  { code: 'uob',                 name: 'UOB Indonesia',               bankCode: '023' },
  { code: 'btpn',                name: 'BTPN',                        bankCode: '213' },
  { code: 'mega',                name: 'Bank Mega',                   bankCode: '426' },
  { code: 'sinarmas',            name: 'Bank Sinarmas',               bankCode: '153' },
  { code: 'bumi-arta',           name: 'Bank Bumi Arta',              bankCode: '076' },
  { code: 'artha-graha',         name: 'Bank Artha Graha Internasional', bankCode: '037' },
  { code: 'mayapada',            name: 'Bank Mayapada',               bankCode: '097' },
  { code: 'mestika-dharma',      name: 'Bank Mestika Dharma',         bankCode: '151' },
  { code: 'ganesha',             name: 'Bank Ganesha',                bankCode: '161' },
  { code: 'maspion',             name: 'Bank Maspion',                bankCode: '157' },
  { code: 'mnc',                 name: 'Bank MNC Internasional',      bankCode: '485' },
  { code: 'kb-bukopin',          name: 'KB Bank (Bukopin)',           bankCode: '441' },
  { code: 'sahabat-sampoerna',   name: 'Bank Sahabat Sampoerna',      bankCode: '523' },
  { code: 'mayora',              name: 'Bank Mayora',                 bankCode: '553' },
  { code: 'multiarta-sentosa',   name: 'Bank Multiarta Sentosa',      bankCode: '548' },
  { code: 'ina-perdana',         name: 'Bank Ina Perdana',            bankCode: '513' },
  { code: 'oke',                 name: 'Bank Oke Indonesia',          bankCode: '526' },
  { code: 'index-selindo',       name: 'Bank Index Selindo',          bankCode: '555' },
  { code: 'victoria',            name: 'Bank Victoria International', bankCode: '566' },
  { code: 'cnb',                 name: 'Bank CNB (Centratama Nasional)', bankCode: '559' },
  { code: 'jasa-jakarta',        name: 'Bank Jasa Jakarta',           bankCode: '472' },
  { code: 'banten',              name: 'Bank Banten',                 bankCode: '137' },

  // Bank digital
  { code: 'jago',                name: 'Bank Jago',                   bankCode: '542' },
  { code: 'seabank',             name: 'SeaBank Indonesia',           bankCode: '535' },
  { code: 'neo-commerce',        name: 'Bank Neo Commerce',           bankCode: '490' },
  { code: 'raya',                name: 'Bank Raya',                   bankCode: '494' },
  { code: 'allo',                name: 'Allo Bank',                   bankCode: '567' },
  { code: 'nobu',                name: 'Bank Nobu',                   bankCode: '503' },
  { code: 'bca-digital',         name: 'Bank BCA Digital (blu)',      bankCode: '501' },
  { code: 'amar',                name: 'Amar Bank',                   bankCode: '531' },
  { code: 'mantap',              name: 'Bank Mandiri Taspen (Mantap)', bankCode: '564' },
  { code: 'superbank',           name: 'Superbank Indonesia',         bankCode: '562' },
  { code: 'krom',                name: 'Krom Bank Indonesia',         bankCode: '459' },

  // Bank syariah
  { code: 'bsi',                 name: 'BSI (Bank Syariah Indonesia)', bankCode: '451' },
  { code: 'muamalat',            name: 'Bank Muamalat',               bankCode: '147' },
  { code: 'bca-syariah',         name: 'BCA Syariah',                 bankCode: '536' },
  { code: 'btpn-syariah',        name: 'BTPN Syariah',                bankCode: '547' },
  { code: 'mega-syariah',        name: 'Bank Mega Syariah',           bankCode: '506' },
  { code: 'panin-dubai-syariah', name: 'Bank Panin Dubai Syariah',    bankCode: '517' },
  { code: 'bukopin-syariah',     name: 'KB Bukopin Syariah',          bankCode: '521' },
  { code: 'bjb-syariah',         name: 'Bank BJB Syariah',            bankCode: '425' },
  { code: 'victoria-syariah',    name: 'Bank Victoria Syariah',       bankCode: '405' },
  { code: 'aladin-syariah',      name: 'Bank Aladin Syariah',         bankCode: '947' },

  // Bank asing
  { code: 'citibank',            name: 'Citibank',                    bankCode: '031' },
  { code: 'hsbc',                name: 'HSBC Indonesia',              bankCode: '087' },
  { code: 'standard-chartered',  name: 'Standard Chartered',          bankCode: '050' },
  { code: 'dbs',                 name: 'DBS Indonesia',               bankCode: '046' },
  { code: 'commonwealth',        name: 'Bank Commonwealth',           bankCode: '950' },
  { code: 'anz',                 name: 'Bank ANZ Indonesia',          bankCode: '061' },
  { code: 'boc',                 name: 'Bank of China Indonesia',     bankCode: '069' },
  { code: 'shinhan',             name: 'Bank Shinhan Indonesia',      bankCode: '152' },
  { code: 'woori-saudara',       name: 'Bank Woori Saudara',          bankCode: '212' },
  { code: 'icbc',                name: 'Bank ICBC Indonesia',         bankCode: '164' },
  { code: 'qnb',                 name: 'Bank QNB Indonesia',          bankCode: '167' },
  { code: 'keb-hana',            name: 'Bank KEB Hana Indonesia',     bankCode: '484' },
  { code: 'chinatrust',          name: 'Bank Chinatrust Indonesia',   bankCode: '949' },
  { code: 'capital',             name: 'Bank Capital Indonesia',      bankCode: '054' },
  { code: 'ccb',                 name: 'Bank CCB Indonesia',          bankCode: '036' },
  { code: 'mufg',                name: 'Bank MUFG Indonesia',         bankCode: '042' },
  { code: 'ibk',                 name: 'Bank IBK Indonesia',          bankCode: '945' },
  { code: 'smbc',                name: 'Bank SMBC Indonesia',         bankCode: '045' },
  { code: 'sbi-indonesia',       name: 'Bank SBI Indonesia',          bankCode: '498' },
  { code: 'boi-indonesia',       name: 'Bank of India Indonesia',     bankCode: '146' },
  { code: 'prima-master',        name: 'Prima Master Bank',           bankCode: '520' },

  // Bank Pembangunan Daerah (BPD)
  { code: 'bjb',                 name: 'Bank BJB',                    bankCode: '110' },
  { code: 'dki',                 name: 'Bank DKI',                    bankCode: '111' },
  { code: 'bpd-diy',             name: 'BPD DIY',                     bankCode: '112' },
  { code: 'jateng',              name: 'Bank Jateng',                 bankCode: '113' },
  { code: 'jatim',               name: 'Bank Jatim',                  bankCode: '114' },
  { code: 'jambi',               name: 'Bank Jambi',                  bankCode: '115' },
  { code: 'aceh-syariah',        name: 'Bank Aceh Syariah',           bankCode: '116' },
  { code: 'sumut',               name: 'Bank Sumut',                  bankCode: '117' },
  { code: 'nagari',              name: 'Bank Nagari (Sumbar)',        bankCode: '118' },
  { code: 'brk-syariah',         name: 'Bank BRK Syariah (Riau Kepri)', bankCode: '119' },
  { code: 'sumsel-babel',        name: 'Bank Sumsel Babel',           bankCode: '120' },
  { code: 'lampung',             name: 'Bank Lampung',                bankCode: '121' },
  { code: 'kalsel',              name: 'Bank Kalsel',                 bankCode: '122' },
  { code: 'kalbar',              name: 'Bank Kalbar',                 bankCode: '123' },
  { code: 'kaltimtara',          name: 'Bank Kaltimtara',             bankCode: '124' },
  { code: 'kalteng',             name: 'Bank Kalteng',                bankCode: '125' },
  { code: 'sulselbar',           name: 'Bank Sulselbar',              bankCode: '126' },
  { code: 'sulut',               name: 'Bank SulutGo',                bankCode: '127' },
  { code: 'ntb-syariah',         name: 'Bank NTB Syariah',            bankCode: '128' },
  { code: 'bpd-bali',            name: 'BPD Bali',                    bankCode: '129' },
  { code: 'ntt',                 name: 'Bank NTT',                    bankCode: '130' },
  { code: 'maluku-malut',        name: 'Bank Maluku Malut',           bankCode: '131' },
  { code: 'papua',               name: 'Bank Papua',                  bankCode: '132' },
  { code: 'bengkulu',            name: 'Bank Bengkulu',               bankCode: '133' },
  { code: 'sulteng',             name: 'Bank Sulteng',                bankCode: '134' },
  { code: 'sultra',              name: 'Bank Sultra',                 bankCode: '135' },

  // BPR (bank perkreditan rakyat) besar
  { code: 'bpr-eka-bumi-artha',        name: 'BPR Eka Bumi Artha',         bankCode: '867' },
  { code: 'bpr-karyajatnika-sadaya',   name: 'BPR Karyajatnika Sadaya',    bankCode: '688' },
  { code: 'bpr-supra-artapersada',     name: 'BPR Supra Artapersada',      bankCode: '600' },

  // Dompet digital (e-wallet) — tidak punya kode kliring baku seperti bank;
  // nomor VA transfernya beda-beda tergantung bank pengirim, jadi tanpa bankCode.
  { code: 'gopay',               name: 'GoPay',            ewallet: true },
  { code: 'ovo',                 name: 'OVO',              ewallet: true },
  { code: 'dana',                name: 'DANA',             ewallet: true },
  { code: 'shopeepay',           name: 'ShopeePay',        ewallet: true },
  { code: 'linkaja',             name: 'LinkAja',          ewallet: true },
  { code: 'sakuku',              name: 'Sakuku (BCA)',     ewallet: true },
  { code: 'isaku',               name: 'i.saku (Indomaret)', ewallet: true },
  { code: 'astrapay',            name: 'AstraPay',         ewallet: true },
  { code: 'doku',                name: 'DOKU Wallet',      ewallet: true },
] as const;
